import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';

const require = createRequire(import.meta.url);
const { chunkText, chunkTechnicalText, retrieveChunks, retrieveChatChunks, chatChunksForMessages, targetChatMessages, technicalTargetMessages, evaluationTurns, scoreExpectedMemory, gapDiagnosisForVerdict, parseScoredVerdict, multiTurnGapDiagnosis, normalizeDatasetCase, sourceIndexedCases, parseSurveyFacts, parseTechnicalAnalysis, hasSourceEvidence, removeDocumentData, removeTechnicalDocumentData, normalizeChat, appendChatMessage, appendSurveyFacts, publicConnection, flexAgentRequest, flexAgentWidgetTokenRequest } = require('./server.js');

const html = readFileSync('index.html', 'utf8');
const css = readFileSync('styles.css', 'utf8');
const js = readFileSync('app.js', 'utf8');
const server = readFileSync('server.js', 'utf8');

assert.match(html, /id="app"/);
assert.match(js, /let uploadedDocument = null/);
assert.match(js, /Customer chat/);
assert.match(js, /Survey memory/);
assert.match(js, /requestSubmit/);
assert.match(js, /customer-question'\)\?\.focus/);
assert.match(js, /activeChatId/);
assert.match(js, /RECENT CHATS/);
assert.match(js, /Write a message/);
assert.match(js, /file-drop"><label for="file-input">Upload document/);
assert.match(js, /Golden datasets/);
assert.match(js, /Welcome to Verity/);
assert.match(js, /Upload a source document/);
assert.match(js, /Four steps from source document to evidence/);
assert.match(js, /const pages = \{ home, evaluation/);
assert.match(html, /data-page="home"/);
assert.ok(html.indexOf('data-page="datasets"') < html.indexOf('data-page="evaluation"'));
assert.ok(html.indexOf('data-page="chat"') < html.indexOf('data-page="settings"'));
assert.match(js, /Instructions for this policy/);
assert.match(css, /prefers-reduced-motion/);
assert.match(server, /aes-256-gcm/);
assert.match(server, /app\.post\('\/api\/connections'/);
assert.match(server, /app\.post\('\/api\/flexagent-target'/);
assert.match(server, /app\.post\('\/api\/flexagent-livekit-token'/);
assert.match(server, /app\.post\('\/api\/evaluations\/livekit'/);
assert.match(html, /vendor\/livekit-client\.js/);
assert.match(server, /app\.post\('\/api\/openai-setup'/);
assert.match(server, /app\.delete\('\/api\/connections\/:id'/);
assert.match(server, /app\.put\('\/api\/connections\/:id\/prompt'/);
assert.match(server, /app\.put\('\/api\/agent-configs'/);
assert.match(server, /agentPrompt/);
assert.match(server, /app\.post\('\/api\/documents'/);
assert.match(server, /app\.post\('\/api\/technical-documents'/);
assert.match(server, /chunkTechnicalText/);
assert.match(server, /RETRIEVED TECHNICAL SECTIONS/);
assert.match(server, /Technical document evaluation requires a model target/);
assert.match(js, /Technical Blueprint/);
assert.match(js, /js-remove-technical-document/);
assert.match(js, /removeTechnicalDocument/);
assert.match(js, /This permanently removes/);
assert.match(js, /Technical documents/);
assert.match(js, /technical-library-scroll/);
assert.match(js, /Document chat/);
assert.match(js, /allDocuments/);
assert.match(js, /operational or technical document/);
assert.match(js, /How it works/);
assert.match(js, /Source evidence/);
assert.match(server, /app\.delete\('\/api\/documents\/:id'/);
assert.match(server, /app\.post\('\/api\/chat'/);
assert.match(server, /targetChatMessages/);
assert.match(server, /extractSurveyFacts/);
assert.match(server, /chats: \[\]/);
assert.match(server, /app\.post\('\/api\/datasets\/generate'/);
assert.match(server, /customer-facing policy evaluation cases/);
assert.match(server, /app\.put\('\/api\/datasets\/:id'/);
assert.match(server, /app\.post\('\/api\/evaluations'/);
assert.match(server, /app\.post\('\/api\/evaluations\/manual'/);
assert.match(server, /function flexAgentRequest/);
assert.match(server, /text-embedding-3-small/);
assert.match(server, /function embedAll/);
assert.match(server, /RETRIEVED POLICY SECTIONS/);
assert.match(server, /store\.chunks/);
assert.match(js, /RAG ready/);
assert.match(js, /Try customer chat/);
assert.match(js, /Create golden dataset/);
assert.match(js, /gpt-5\.6-luna/);
assert.match(js, /gpt-5\.6-terra/);
assert.match(js, /Generating scenarios/);
assert.match(js, /Review draft/);
assert.match(js, /Review golden dataset/);
assert.match(js, /Add scenario/);
assert.match(js, /Remove scenario/);
assert.match(js, /Go to evaluation/);
assert.match(js, /Save & approve/);
assert.match(js, /Viewing evaluation/);
assert.match(js, /Target answer/);
assert.match(js, /Score pasted agent answers/);
assert.match(js, /MANUAL FLEXAGENT TEST/);
assert.match(js, /runManualEvaluation/);
assert.match(js, /no retrieval trace was captured/);
assert.match(js, /Download report/);
assert.match(js, /downloadEvaluationReport/);
assert.match(js, /RAG investigation/);
assert.match(js, /gapDiagnosisMarkup\(item\)/);
assert.match(js, /evaluationSummaryMarkup\(latest\)/);
assert.match(js, /evaluationSummaryMarkup\(evaluation\)/);
assert.match(js, /Review evidence, not just a score/);
assert.match(js, /viewingEvaluationId = body.id/);
assert.match(js, /View retrieved policy sections/);
assert.match(js, /Rubric/);
assert.match(js, /FlexAgent target/);
assert.match(js, /flexagent-form/);
assert.match(js, /FlexAgent used its own knowledge base/);
assert.match(js, /LiveKit widget path/);
assert.match(js, /liveKitAnswer/);
const flexAgentTarget = publicConnection({ id: 'conn_flex', role: 'target', kind: 'flexagent', name: 'FlexAgent', baseUrl: 'http://127.0.0.1:3000', orgId: '65f000000000000000000001', agentId: '65f000000000000000000002', secret: { iv: 'private', tag: 'private', authTag: 'private' } });
assert.equal(flexAgentTarget.kind, 'flexagent');
assert.equal(flexAgentTarget.orgId, '65f000000000000000000001');
assert.equal(flexAgentTarget.secret, undefined);
assert.deepEqual(flexAgentRequest(flexAgentTarget, 'How many vacation days do I get?'), {
  url: 'http://127.0.0.1:3000/v1/evaluation/answer',
  body: { orgId: '65f000000000000000000001', agentId: '65f000000000000000000002', question: 'How many vacation days do I get?' }
});
const liveKitTarget = publicConnection({ id: 'conn_livekit', role: 'target', kind: 'flexagent-livekit', name: 'FlexAgent widget', baseUrl: 'http://127.0.0.1:3000', orgId: '65f000000000000000000001', agentId: '65f000000000000000000002' });
assert.deepEqual(flexAgentWidgetTokenRequest({ ...liveKitTarget, parentOrigin: 'http://127.0.0.1:4173' }), {
  url: 'http://127.0.0.1:3000/v1/livekit/token',
  body: { orgId: '65f000000000000000000001', agentId: '65f000000000000000000002', parentOrigin: 'http://127.0.0.1:4173' }
});
const chunks = chunkText('First policy section. '.repeat(120), 120, 20);
assert.ok(chunks.length > 1);
assert.ok(chunks.every(chunk => chunk.text.length <= 120));
const technicalChunks = chunkTechnicalText('## Lookup API\nUse `find_stop(place)` before departures.\n```json\n{"place":"Boston"}\n```\n\n## Departures\nCall departures_for_date(stopId).', 140, 20);
assert.equal(technicalChunks.length, 2);
assert.match(technicalChunks[0].text, /Lookup API/);
assert.match(technicalChunks[0].text, /\{"place":"Boston"\}/);
const ranked = retrieveChunks([{ documentId: 'doc_1', text: 'best', vector: [1, 0] }, { documentId: 'doc_1', text: 'other', vector: [0, 1] }, { documentId: 'doc_2', text: 'wrong document', vector: [1, 0] }], 'doc_1', [1, 0], 2);
assert.deepEqual(ranked.map(chunk => chunk.text), ['best', 'other']);
const kindRanked = retrieveChunks([{ documentId: 'same', documentKind: 'technical', text: 'technical', vector: [1, 0] }, { documentId: 'same', documentKind: 'policy', text: 'policy', vector: [1, 0] }], 'same', [1, 0], 5, 'technical');
assert.deepEqual(kindRanked.map(chunk => chunk.text), ['technical']);
const history = retrieveChatChunks([{ chatId: 'chat_1', text: 'My name is Sam.', vector: [1, 0] }, { chatId: 'chat_1', text: 'I live in Boston.', vector: [0, 1] }, { chatId: 'chat_2', text: 'Wrong chat.', vector: [1, 0] }], 'chat_1', [1, 0]);
assert.deepEqual(history.map(chunk => chunk.text), ['My name is Sam.', 'I live in Boston.']);
const store = { documents: [{ id: 'doc_1' }, { id: 'doc_2' }], chunks: [{ documentId: 'doc_1' }, { documentId: 'doc_2' }], chatChunks: [{ documentId: 'doc_1' }, { documentId: 'doc_2' }], datasets: [{ id: 'set_1', documentId: 'doc_1' }], evaluations: [{ datasetId: 'set_1' }], chats: [{ documentId: 'doc_1' }], agentConfigs: [{ documentId: 'doc_1' }] };
assert.equal(removeDocumentData(store, 'doc_1'), true);
assert.deepEqual(store.chunks, [{ documentId: 'doc_2' }]);
assert.deepEqual(store.chatChunks, [{ documentId: 'doc_2' }]);
assert.equal(store.documents.length, 1);
assert.equal(store.datasets.length + store.evaluations.length + store.chats.length + store.agentConfigs.length, 0);
const technicalStore = { technicalDocuments: [{ id: 'tech_1' }, { id: 'tech_2' }], chunks: [{ documentId: 'tech_1' }, { documentId: 'tech_2' }], datasets: [{ id: 'set_tech', documentId: 'tech_1' }], evaluations: [{ datasetId: 'set_tech' }], chats: [{ documentId: 'tech_1' }], agentConfigs: [{ documentId: 'tech_1' }] };
assert.equal(removeTechnicalDocumentData(technicalStore, 'tech_1'), true);
assert.deepEqual(technicalStore.technicalDocuments, [{ id: 'tech_2' }]);
assert.deepEqual(technicalStore.chunks, [{ documentId: 'tech_2' }]);
const withMessage = appendChatMessage({ messages: [] }, 'user', 'I live in Boston.', '2026-09-21T12:00:00.000Z');
assert.equal(withMessage.messages.length, 1);
assert.match(withMessage.messages[0].id, /^msg_/);
assert.equal(withMessage.messages[0].createdAt, '2026-09-21T12:00:00.000Z');
const legacyChat = normalizeChat({ id: 'chat_legacy', createdAt: '2026-09-20T12:00:00.000Z', messages: [{ role: 'user', content: 'I am Casey.' }] });
assert.match(legacyChat.messages[0].id, /^msg_legacy_/);
assert.equal(legacyChat.messages[0].createdAt, '2026-09-20T12:00:00.000Z');
assert.deepEqual(legacyChat.surveyMemory, { version: 1, facts: [] });
const chat = { id: 'chat_1', messages: [{ id: 'msg_1', role: 'user', content: 'My name is Sam.' }], surveyMemory: { version: 1, facts: [] } };
const remembered = appendSurveyFacts(chat, [{ kind: 'explicit', value: 'Sam', sourceMessageId: 'msg_1', status: 'active' }], '2026-09-21T12:00:00.000Z');
assert.equal(remembered.messages, chat.messages);
assert.deepEqual(remembered.surveyMemory.facts[0], { id: 'memory_1', kind: 'explicit', value: 'Sam', sourceMessageId: 'msg_1', status: 'active', createdAt: '2026-09-21T12:00:00.000Z' });
const corrected = appendSurveyFacts({ ...remembered, messages: [...remembered.messages, { id: 'msg_2', role: 'user', content: 'Actually, my name is Samuel.' }] }, [{ kind: 'explicit', value: 'Samuel', sourceMessageId: 'msg_2', status: 'active', supersedes: 'memory_1' }], '2026-09-21T12:01:00.000Z');
assert.equal(corrected.surveyMemory.facts.length, 2);
assert.equal(corrected.surveyMemory.facts[0].status, 'superseded');
assert.equal(corrected.surveyMemory.facts[1].supersedes, 'memory_1');
const targetMessages = targetChatMessages('Follow the survey rules.', [{ text: 'Rule A' }], corrected, history);
assert.match(targetMessages[0].content, /EXPLICIT SURVEY MEMORY/);
assert.match(targetMessages[0].content, /Samuel/);
assert.match(targetMessages[0].content, /RELEVANT EARLIER CONVERSATION/);
assert.match(targetMessages[0].content, /My name is Sam/);
assert.match(technicalTargetMessages('Answer from the technical source.', [{ text: 'Use find_stop first.' }], 'How do I get departures?')[0].content, /RETRIEVED TECHNICAL SECTIONS/);
assert.deepEqual(chatChunksForMessages(corrected, 'doc_1', corrected.messages, [[1, 0], [0, 1]]).map(chunk => ({ chatId: chunk.chatId, messageId: chunk.messageId, text: chunk.text, vector: chunk.vector })), [
  { chatId: 'chat_1', messageId: 'msg_1', text: 'My name is Sam.', vector: [1, 0] },
  { chatId: 'chat_1', messageId: 'msg_2', text: 'Actually, my name is Samuel.', vector: [0, 1] },
]);
assert.throws(() => appendSurveyFacts(chat, [{ kind: 'explicit', value: 'Taylor', sourceMessageId: 'missing', status: 'active' }]), /source message/);
assert.deepEqual(chat.surveyMemory.facts, []);
assert.deepEqual(parseSurveyFacts('{"facts":[{"kind":"explicit","value":"Sam","sourceMessageId":"msg_1","status":"active"}]}'), [{ kind: 'explicit', value: 'Sam', sourceMessageId: 'msg_1', status: 'active' }]);
assert.throws(() => parseSurveyFacts('{"facts":"not an array"}'), /facts/);
const technicalSource = 'When a rider asks for arrivals, call find_stop then departures_for_date.';
assert.deepEqual(parseTechnicalAnalysis(JSON.stringify({ overview: { purpose: 'Find arrivals', systems: ['Transit API'], keyRules: ['Find stop first'], unknowns: [], sourceEvidence: 'rider asks for arrivals' }, flows: [{ trigger: 'Arrival question', action: 'find_stop', result: 'Stop ID', sourceEvidence: 'call find_stop' }], catalog: [{ name: 'find_stop', purpose: 'Find a stop', whenToCall: 'Before arrivals', inputs: 'Place', outputs: 'Stop ID', dependencies: '', sourceEvidence: 'find_stop' }], examples: [{ input: 'arrivals', output: 'Stop ID', sourceEvidence: 'rider asks for arrivals' }] }), technicalSource).overview.purpose, 'Find arrivals');
assert.throws(() => parseTechnicalAnalysis(JSON.stringify({ overview: { purpose: 'x' }, flows: [{ sourceEvidence: 'invented' }], catalog: [], examples: [] }), technicalSource), /source/i);
assert.deepEqual(normalizeDatasetCase({ question: 'Can I reschedule?', expectedAnswer: 'Yes.', requiredPoints: ['Give the rule'], forbiddenPoints: [], sourceEvidence: 'Section 2.' }), { question: 'Can I reschedule?', expectedAnswer: 'Yes.', requiredPoints: ['Give the rule'], forbiddenPoints: [], sourceEvidence: 'Section 2.', turns: [], expectedFinalMemory: [] });
assert.throws(() => normalizeDatasetCase({ turns: [{ userMessage: '' }] }), /user message/);
assert.equal(hasSourceEvidence('A documented API\nreturns an ID.', 'API returns an ID.'), true);
assert.equal(hasSourceEvidence('A documented API returns an ID.', 'invented evidence'), false);
assert.equal(sourceIndexedCases(JSON.stringify({ cases: [{ question: 'What does it return?', expectedAnswer: 'An ID.', sourceIndex: 2 }] }), [{ text: 'Unrelated.' }, { text: 'The API returns an ID.' }])[0].sourceEvidence, 'The API returns an ID.');
assert.deepEqual(evaluationTurns({ question: 'My name is Sam.', expectedAnswer: 'Thanks, Sam.', requiredPoints: [], forbiddenPoints: [], sourceEvidence: 'Survey.' }), [{ userMessage: 'My name is Sam.', expectedAnswer: 'Thanks, Sam.', requiredPoints: [], forbiddenPoints: [], sourceEvidence: 'Survey.' }]);
assert.deepEqual(scoreExpectedMemory(['Samuel'], corrected.surveyMemory), { pass: true, missing: [] });
const gapVerdict = { score: 10, pass: false, missingPoints: ['Point A', 'Point B', 'Point C'], forbiddenClaims: [], rationale: 'Most facts absent.' };
const rubric = { requiredPoints: ['Point A', 'Point B', 'Point C'] };
const fullMiss = gapDiagnosisForVerdict(gapVerdict, rubric);
assert.deepEqual(fullMiss.categories, ['Likely retrieval miss']);
assert.match(fullMiss.teamFocus, /top retrieved chunks/);
assert.doesNotMatch(`${fullMiss.why} ${fullMiss.teamFocus}`, /Point A|Point B|Point C/);
assert.deepEqual(gapDiagnosisForVerdict({ ...gapVerdict, missingPoints: ['Point A'] }, rubric).categories, ['Partial retrieval coverage']);
assert.deepEqual(gapDiagnosisForVerdict({ ...gapVerdict, missingPoints: [], forbiddenClaims: ['Unsupported claim'] }, rubric).categories, ['Answer grounding gap', 'Unsupported or conflicting answer']);
assert.equal(parseScoredVerdict(JSON.stringify({ ...gapVerdict, gapDiagnosis: { categories: ['Incomplete answer'], why: 'old', teamFocus: 'old' } })).gapDiagnosis, undefined);
assert.equal(parseScoredVerdict(JSON.stringify({ ...gapVerdict, pass: true })).gapDiagnosis, undefined);
const combinedDiagnosis = multiTurnGapDiagnosis([{ ...gapVerdict, turn: rubric }], { pass: false, missing: ['customer name'] });
assert.deepEqual(combinedDiagnosis.categories, ['Likely retrieval miss', 'Conversation memory gap']);
assert.match(combinedDiagnosis.why, /3 of 3.*1 expected conversation detail/);
assert.equal(multiTurnGapDiagnosis([{ pass: true }], { pass: true, missing: [] }), undefined);
console.log('Workspace checks passed.');
